extends SceneTree

const GameStateScript := preload("res://src/core/game_state.gd")
const CountryStateScript := preload("res://src/core/country_state.gd")
const PolicyResolverScript := preload("res://src/core/policy_resolver.gd")
const PublicChoiceResolverScript := preload("res://src/core/public_choice_resolver.gd")
const WorldResolverScript := preload("res://src/core/world_resolver.gd")

var had_failure := false

func _init() -> void:
	var game = GameStateScript.new()
	game.new_game()
	for country in game.countries:
		_assert(country.deck.size() + country.hand.size() + country.discard.size() == 12, "%s starts with a 12-card state deck" % country.display_name)
		_assert(_policy_count(country.deck) + _policy_count(country.hand) + _policy_count(country.discard) == 0, "%s state deck contains no policy cards" % country.display_name)
		_assert(country.policy_menu.size() >= 12, "%s has a persistent policy menu" % country.display_name)
		_assert(_policy_catalog_menu_count(country) >= 12 and _policy_catalog_menu_count(country) <= 15, "%s starts with a 12-15 card policy catalog" % country.display_name)
		_assert(country.active_agenda.size() >= 5 and country.active_agenda.size() <= 8, "%s has a bounded active policy agenda" % country.display_name)
		_assert(_basic_policy_count(country.active_agenda) == 5, "%s keeps every basic policy as an agenda safety valve" % country.display_name)
		_assert(_all_agenda_from_catalog_or_basic(country), "%s active agenda is generated from basic policies or the policy catalog" % country.display_name)
		_assert(_all_policy_menu_sources_present(country), "%s policy menu records the source of every option" % country.display_name)
		_assert(_policy_menu_has_source(country, "module:"), "%s has policy options generated by its country modules" % country.display_name)
		_assert(not _policy_menu_has_source(country, "filler"), "%s does not pad policy options with generic fillers" % country.display_name)
	_assert(game.current_phase() == "negotiation", "game starts before policy input")
	var initial_selection: Dictionary = game.countries[0].selected_policy
	var opening_agenda_ids := []
	for country in game.countries:
		opening_agenda_ids.append(_policy_ids(country.active_agenda))
	game.select_policy(0, 0)
	_assert(game.countries[0].selected_policy == initial_selection, "policy selection is blocked outside policy planning")

	game.advance_phase()
	for i in range(game.countries.size()):
		_assert(_policy_ids(game.countries[i].active_agenda) == opening_agenda_ids[i], "%s policy agenda survives negotiation instead of drawing and discarding invisible catalog cards" % game.countries[i].display_name)
	game.select_policy(0, 0)
	_assert(not game.countries[0].selected_policy.is_empty(), "policy selection is allowed during policy planning")
	var initial_worker: String = game.countries[0].assigned_worker
	game.assign_worker(0, "diplomat")
	_assert(game.countries[0].assigned_worker == initial_worker, "worker assignment is blocked outside worker assignment")

	game.advance_phase()
	game.assign_worker(0, "diplomat")
	_assert(game.countries[0].assigned_worker == "diplomat", "worker assignment is allowed during worker assignment")
	game.toggle_worker(0, "bureaucrats")
	_assert(game.countries[0].assigned_worker_list().has("diplomat") and game.countries[0].assigned_worker_list().has("bureaucrats"), "worker assignment supports multiple workers")
	var basic_policy: Dictionary = _first_basic_policy(game.countries[0].active_agenda)
	_assert(not basic_policy.is_empty(), "active agenda keeps a basic policy safety valve")
	game.countries[0].put_policy_on_cooldown(basic_policy, 3)
	_assert(game.countries[0].is_policy_available(basic_policy), "basic policies remain available even after use")

	var response_country = CountryStateScript.new()
	response_country.display_name = "対応国"
	response_country.tracks = {"gdp_gap": 0, "inflation": 2, "expected_inflation": 2, "unemployment": 3, "debt": 0, "financial_stress": 0, "political_capital": 5, "exchange_rate": 0, "current_account": 0, "influence": 0}
	response_country.assign_workers(["bureaucrats"])
	var response_policy := {"id": "response_probe", "display_name": "需要対応", "type": "policy", "tags": ["demand"], "costs": {}, "effects": {"country": {}, "world": {}}}
	response_country.hand = [
		{"id": "state_probe_a", "display_name": "状態プローブA", "type": "vulnerability", "response": {"removed_by_tags": ["demand"], "extra_costs": {"political": 1}}},
		{"id": "state_probe_b", "display_name": "状態プローブB", "type": "vulnerability", "response": {"removed_by_tags": ["demand"], "extra_costs": {"political": 1}}}
	]
	response_country.selected_response_index = 1
	PolicyResolverScript.resolve_paid_policy(response_country, [response_country], game.world, response_policy, {}, {"success": true, "shortages": {}, "costs": {}})
	_assert(response_country.hand.size() == 1 and String(response_country.hand[0].get("id", "")) == "state_probe_a", "response task removes the explicitly selected vulnerability from hand")
	_assert(int(response_country.tracks.get("political_capital", 0)) == 4, "response task pays its extra political cost")

	var target_game = GameStateScript.new()
	target_game.new_game()
	target_game.advance_phase()
	var target_policy := {
		"id": "target_probe",
		"type": "policy",
		"display_name": "対象政策",
		"target": "country",
		"costs": {},
		"effects": {
			"donor": {"influence": 2},
			"recipient": {"financial_stress": -2, "exchange_rate": 1},
			"world": {"global_coordination": 1}
		}
	}
	_seed_test_agenda(target_game.countries[0], [target_policy])
	target_game.select_policy(0, 0)
	_assert(target_game.countries[0].selected_target_index == 1, "targeted policies receive a default non-self target")
	target_game.select_policy_target(0, 2)
	_assert(target_game.countries[0].selected_target_index == 2, "targeted policies can designate another country")
	target_game.countries[0].tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 0, "political_capital": 10, "exchange_rate": 0, "current_account": 0, "influence": 0}
	target_game.countries[2].tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 4, "political_capital": 10, "exchange_rate": 0, "current_account": 0, "influence": 0}
	PolicyResolverScript.resolve_policy(target_game.countries[0], target_game.countries, target_game.world, target_policy, {})
	_assert(int(target_game.countries[0].tracks.get("influence", 0)) == 2, "targeted policy applies donor effects to the source")
	_assert(int(target_game.countries[2].tracks.get("financial_stress", 0)) == 2, "targeted policy applies recipient effects to the designated country")
	_assert(int(target_game.countries[2].tracks.get("exchange_rate", 0)) == 1, "targeted policy applies recipient exchange-rate support")

	var support_game = GameStateScript.new()
	support_game.new_game()
	support_game.request_support(0, "debt")
	support_game.pledge_support(1, 0, "debt")
	support_game.advance_phase()
	var debt_support_policy := {"id": "debt_support_probe", "display_name": "債務支援", "type": "policy", "tags": ["debt"], "costs": {}, "effects": {"country": {}, "world": {}}}
	support_game.countries[0].tracks["debt"] = 4
	support_game.countries[0].tracks["financial_stress"] = 4
	_seed_test_agenda(support_game.countries[1], [debt_support_policy])
	support_game.select_policy(1, 0)
	support_game.countries[0].selected_policy = {"id": "neutral_probe", "display_name": "中立", "type": "policy", "tags": [], "costs": {}, "effects": {"country": {}, "world": {}}}
	var support_log: Array = support_game._resolve_support_pledges(support_game.countries)
	_assert(_contains(support_log, "支援要請"), "fulfilled support pledges are logged")
	_assert(int(support_game.countries[1].tracks.get("influence", 0)) >= 1, "fulfilled support pledges reward the supporter with influence")
	_assert(int(support_game.countries[0].tracks.get("debt", 0)) == 3 and int(support_game.countries[0].tracks.get("financial_stress", 0)) == 3, "fulfilled debt support helps the requester")

	var agenda_trim_game = GameStateScript.new()
	agenda_trim_game.new_game()
	var declared_policy := {"id": "declared_probe", "display_name": "宣言政策", "type": "policy", "tags": ["cooperation"], "costs": {}, "effects": {"country": {}, "world": {}}}
	agenda_trim_game.countries[0].policy_catalog_deck = [declared_policy]
	agenda_trim_game.countries[0].declared_agenda = "cooperation"
	agenda_trim_game._refresh_active_agendas_after_negotiation()
	_assert(_agenda_has(agenda_trim_game.countries[0], "declared_probe"), "declared/support policy receives priority and is not trimmed out of a full agenda")
	_assert(_basic_policy_count(agenda_trim_game.countries[0].active_agenda) == 5, "declared/support policy priority does not trim basic safety valves")
	_assert(agenda_trim_game.countries[0].active_agenda.size() <= 8, "declared/support policy priority still respects the agenda size cap")

	var pledge_agenda_game = GameStateScript.new()
	pledge_agenda_game.new_game()
	var pledged_policy := {"id": "pledged_debt_probe", "display_name": "支援議題", "type": "policy", "tags": ["debt"], "costs": {}, "effects": {"country": {}, "world": {}}}
	pledge_agenda_game.countries[1].policy_catalog_deck = [pledged_policy]
	pledge_agenda_game.pledge_support(1, 0, "debt")
	pledge_agenda_game._refresh_active_agendas_after_negotiation()
	_assert(_agenda_has(pledge_agenda_game.countries[1], "pledged_debt_probe"), "support pledges surface matching catalog policies into the agenda")

	var pressure_agenda_game = GameStateScript.new()
	pressure_agenda_game.new_game()
	var pressure_policy := {"id": "pressure_trade_probe", "display_name": "圧力議題", "type": "policy", "tags": ["trade"], "costs": {}, "effects": {"country": {}, "world": {}}}
	pressure_agenda_game.countries[0].policy_catalog_deck = [pressure_policy]
	pressure_agenda_game.countries[0].policy_catalog_discard = []
	pressure_agenda_game.countries[0].domestic_pressure = {"display_name": "通商圧力", "demand": {"preferred_policy_tags": ["trade"]}}
	pressure_agenda_game._build_active_agendas()
	_assert(_agenda_has(pressure_agenda_game.countries[0], "pressure_trade_probe"), "domestic pressure surfaces matching catalog policies into the agenda")

	var country = CountryStateScript.new()
	country.display_name = "試験国"
	country.tracks = {"gdp_gap": -2, "inflation": 1, "expected_inflation": 1, "unemployment": 8, "debt": 9, "financial_stress": 8, "political_capital": 0, "exchange_rate": -3, "current_account": -3, "influence": 0}
	country.assigned_worker = "bureaucrats"
	var world = game.world
	var policy := {
		"display_name": "高難度政策",
		"costs": {"political": 2, "fiscal": 2, "administrative": 3, "credibility": 3, "international": 3, "industrial": 3},
		"effects": {"country": {"gdp_gap": 2}, "world": {"world_demand": 1}}
	}
	var log := PolicyResolverScript.resolve_policy(country, [], world, policy, {})
	_assert(_contains(log, "延期"), "administrative shortage delays policy resolution")
	_assert(_contains(log, "行政能力不足"), "administrative shortage is logged")
	_assert(_contains(log, "信認不足"), "credibility shortage is logged")
	_assert(_contains(log, "国際調整不足"), "international shortage is logged")
	_assert(_contains(log, "産業実行力不足"), "industrial shortage is logged")
	_assert(country.pending_effects.size() == 1, "administrative shortage creates a pending implementation")
	var pending_before := int(country.tracks.get("gdp_gap", 0))
	game.countries = [country]
	game.world = world
	var pending_log: Array = game._resolve_pending_effects()
	_assert(_contains(pending_log, "実施ラグ"), "pending implementation fires on the next start turn")
	_assert(int(country.tracks.get("gdp_gap", 0)) > pending_before, "pending implementation applies delayed country effects")
	game.new_game()

	var liquidity_country = CountryStateScript.new()
	liquidity_country.display_name = "流動性国"
	liquidity_country.tracks = {"gdp_gap": -2, "inflation": -1, "expected_inflation": -1, "unemployment": 4, "debt": 2, "financial_stress": 0, "political_capital": 8, "exchange_rate": 0, "current_account": 0, "influence": 0}
	var monetary_policy := {"display_name": "緩和", "tags": ["monetary"], "costs": {}, "effects": {"country": {"gdp_gap": 2}, "world": {}}}
	PolicyResolverScript.resolve_policy(liquidity_country, [], world, monetary_policy, {})
	_assert(int(liquidity_country.tracks.get("gdp_gap", 0)) == -1, "liquidity trap reduces monetary gdp effect")

	var pressure_country = CountryStateScript.new()
	pressure_country.display_name = "圧力国"
	pressure_country.tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 0, "political_capital": 0, "exchange_rate": 0, "current_account": 0, "influence": 0}
	pressure_country.domestic_pressure = {"display_name": "試験圧力", "demand": {"preferred_policy_tags": ["fiscal"], "if_satisfied": {"political_capital": 1}, "if_ignored": {"political_capital": -1}}}
	var pressure_log := PublicChoiceResolverScript.resolve_pressure(pressure_country, {"tags": ["fiscal"]}, false)
	_assert(int(pressure_country.tracks.get("political_capital", 0)) == -1, "failed policies do not satisfy matching domestic pressure")
	_assert(pressure_log.contains("無視"), "failed pressure match is logged as ignored")
	pressure_country.tracks["political_capital"] = 0
	pressure_log = PublicChoiceResolverScript.resolve_pressure(pressure_country, {"tags": ["fiscal"]}, "subsidized")
	_assert(int(pressure_country.tracks.get("political_capital", 0)) == 1, "subsidized policies partially satisfy matching domestic pressure")
	_assert(pressure_log.contains("部分的"), "partial pressure match is logged")

	var mutation_country = CountryStateScript.new()
	mutation_country.display_name = "変質国"
	mutation_country.tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 0, "political_capital": 10, "exchange_rate": 0, "current_account": 0, "influence": 0}
	var mutation_policy := {
		"display_name": "変質政策",
		"costs": {},
		"effects": {"country": {}, "world": {}},
		"mutations": {"add_to_deck": ["productivity_growth", "vested_interest_backlash"]}
	}
	var mutation_cards := {
		"productivity_growth": {"id": "productivity_growth", "display_name": "生産性上昇"},
		"vested_interest_backlash": {"id": "vested_interest_backlash", "display_name": "既得権益の反発"}
	}
	PolicyResolverScript.resolve_policy(mutation_country, [], world, mutation_policy, mutation_cards)
	_assert(String(mutation_country.deck[0].get("id", "")) == "productivity_growth", "deck mutations are placed on top in listed order")
	_assert(String(mutation_country.deck[1].get("id", "")) == "vested_interest_backlash", "all deck mutations are placed on top")

	var catalog_country = CountryStateScript.new()
	catalog_country.display_name = "政策変質国"
	catalog_country.tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 0, "political_capital": 10, "exchange_rate": 0, "current_account": 0, "influence": 0}
	var obsolete_policy := {"id": "obsolete_probe", "display_name": "旧政策", "type": "policy", "tags": ["old"], "costs": {}, "effects": {"country": {}, "world": {}}}
	var stale_policy := {"id": "stale_probe", "display_name": "未制度化政策", "type": "policy", "tags": ["stale"], "costs": {}, "effects": {"country": {}, "world": {}}}
	catalog_country.policy_menu = [obsolete_policy.duplicate(true), stale_policy.duplicate(true)]
	catalog_country.policy_catalog_deck = [obsolete_policy.duplicate(true)]
	catalog_country.policy_catalog_discard = [stale_policy.duplicate(true)]
	catalog_country.active_agenda = [obsolete_policy.duplicate(true)]
	catalog_country.policy_cooldowns = {"obsolete_probe": 2}
	var catalog_policy_index := {
		"institutionalized_reform": {"id": "institutionalized_reform", "display_name": "制度化改革", "type": "policy", "tags": ["reform"], "costs": {}, "effects": {"country": {}, "world": {}}},
		"captured_reform": {"id": "captured_reform", "display_name": "歪んだ改革", "type": "policy", "tags": ["captured"], "costs": {}, "effects": {"country": {}, "world": {}}}
	}
	var catalog_mutation_policy := {
		"display_name": "政策カタログ変質",
		"costs": {},
		"effects": {"country": {}, "world": {}},
		"mutations": {
			"add_to_policy_catalog": ["institutionalized_reform"],
			"remove_from_policy_catalog": ["obsolete_probe"],
			"replace_in_policy_catalog": [{"from": "stale_probe", "to": "captured_reform"}]
		}
	}
	var catalog_log: Array = PolicyResolverScript.resolve_policy(catalog_country, [], world, catalog_mutation_policy, {}, catalog_policy_index)
	_assert(_policy_menu_has(catalog_country, "institutionalized_reform") and _policy_catalog_has(catalog_country, "institutionalized_reform"), "policy mutations add policy catalog cards")
	_assert(not _policy_menu_has(catalog_country, "obsolete_probe") and not _policy_catalog_has(catalog_country, "obsolete_probe"), "policy mutations remove policy catalog cards from all zones")
	_assert(_policy_menu_has(catalog_country, "captured_reform") and _policy_catalog_has(catalog_country, "captured_reform") and not _policy_catalog_has(catalog_country, "stale_probe"), "policy mutations can replace policy catalog cards")
	_assert(not catalog_country.policy_cooldowns.has("obsolete_probe"), "removing policy catalog cards clears cooldowns")
	_assert(_contains(catalog_log, "政策カタログ"), "policy catalog mutations are logged")

	var outcome_country = CountryStateScript.new()
	outcome_country.display_name = "結果別政策国"
	outcome_country.tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 0, "political_capital": 10, "exchange_rate": 0, "current_account": 0, "influence": 0}
	var outcome_policy_index := {
		"clean_reform_probe": {"id": "clean_reform_probe", "display_name": "制度化改革", "type": "policy", "tags": ["reform"], "costs": {}, "effects": {"country": {}, "world": {}}},
		"captured_reform_probe": {"id": "captured_reform_probe", "display_name": "妥協改革", "type": "policy", "tags": ["captured"], "costs": {}, "effects": {"country": {}, "world": {}}}
	}
	var outcome_policy := {
		"display_name": "結果別変質政策",
		"costs": {"political": 2},
		"effects": {"country": {}, "world": {}},
		"mutations_by_resolution": {
			"full": {"add_to_policy_catalog": ["clean_reform_probe"]},
			"softened": {"add_to_policy_catalog": ["captured_reform_probe"]}
		}
	}
	PolicyResolverScript.resolve_paid_policy(outcome_country, [], world, outcome_policy, {}, {"success": true, "shortages": {}, "costs": {"political": 2}}, outcome_policy_index)
	_assert(_policy_catalog_has(outcome_country, "clean_reform_probe"), "full policy resolution can add clean catalog variants")
	_assert(int(outcome_country.tracks.get("political_capital", 0)) == 10, "resolution-specific mutations do not pay policy costs a second time")
	var softened_country = CountryStateScript.new()
	softened_country.display_name = "骨抜き政策国"
	softened_country.tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 0, "political_capital": 10, "exchange_rate": 0, "current_account": 0, "influence": 0}
	PolicyResolverScript.resolve_paid_policy(softened_country, [], world, outcome_policy, {}, {"success": false, "shortages": {"credibility": 1}, "costs": {"political": 2}}, outcome_policy_index)
	_assert(_policy_catalog_has(softened_country, "captured_reform_probe"), "softened policy resolution can add captured catalog variants")

	var spillover_policy := {
		"id": "spillover_probe",
		"display_name": "先行波及",
		"type": "policy",
		"tags": ["cooperation"],
		"costs": {},
		"effects": {"country": {}, "world": {}},
		"spillovers": [{"target_tag": "victim", "effects": {"financial_stress": 10}}]
	}
	var costly_policy := {
		"id": "credibility_probe",
		"display_name": "信認政策",
		"type": "policy",
		"tags": ["cooperation"],
		"costs": {"credibility": 3},
		"effects": {"country": {"gdp_gap": 4}, "world": {}}
	}
	for active_country in game.countries:
		active_country.hand = []
		active_country.selected_policy = {}
		active_country.assigned_worker = "bureaucrats"
		active_country.tracks = {"gdp_gap": 0, "inflation": 0, "expected_inflation": 0, "unemployment": 0, "debt": 0, "financial_stress": 0, "political_capital": 10, "exchange_rate": 0, "current_account": 0, "influence": 0}
	game.world.tracks = {"world_demand": 0, "world_interest_rate": 0, "trade_openness": 5, "international_financial_instability": 0, "depression": 0, "protectionism": 0, "global_coordination": 0}
	_seed_test_agenda(game.countries[0], [spillover_policy])
	game.countries[0].selected_policy = spillover_policy
	game.countries[1].tags = ["victim"]
	_seed_test_agenda(game.countries[1], [costly_policy])
	game.countries[1].selected_policy = costly_policy
	game.countries[0].declared_agenda = "cooperation"
	game.countries[1].declared_agenda = "cooperation"
	game.turn = game.turn_limit
	game.resolve_turn()
	_assert(int(game.countries[1].tracks.get("gdp_gap", 0)) >= 4, "simultaneous reveal freezes policy affordability before spillovers")
	_assert(int(game.countries[0].tracks.get("influence", 0)) == 1, "kept joint declarations add influence")
	_assert(int(game.world.tracks.get("world_demand", 0)) > 0, "kept joint declarations support world demand")
	_assert(game.countries[0].welfare_history.size() == 1, "resolved turns record welfare points")
	_assert(game.countries[0].track_history.size() >= 2, "resolved turns record track history")

	var election_game = GameStateScript.new()
	election_game.new_game()
	election_game.turn = election_game.countries[0].election_turn
	election_game.countries[0].tracks["political_capital"] = 1
	election_game.countries[0].pending_effects = [{"turns": 1, "display_name": "延期政策", "country": {"gdp_gap": 2}, "world": {}}]
	var election_log: Array = election_game._resolve_elections()
	_assert(_contains(election_log, "政権交代"), "low political capital loses an election")
	_assert(int(election_game.countries[0].tracks.get("political_capital", 0)) == 4, "election turnover resets political capital")
	_assert(election_game.countries[0].pending_effects.is_empty(), "election turnover drops one pending reform")

	var crisis_game = GameStateScript.new()
	crisis_game.new_game()
	crisis_game.world.tracks = {"world_demand": 0, "world_interest_rate": 0, "trade_openness": 5, "international_financial_instability": 0, "depression": 0, "protectionism": 0, "global_coordination": 0}
	crisis_game.world.event_deck = [{
		"id": "test_persistent_crisis",
		"display_name": "試験持続危機",
		"message": "試験",
		"effects": {"world": {"international_financial_instability": 1}},
		"persistent_crisis": {
			"duration": 2,
			"clear_text": "協調4",
			"clear_when": {"world_min": {"global_coordination": 4}},
			"effects": {"world": {"international_financial_instability": 1}}
		}
	}]
	crisis_game.world.event_discard = []
	WorldResolverScript.reveal_event(crisis_game.world, crisis_game.countries, crisis_game.rng)
	_assert(crisis_game.world.active_crises.size() == 1, "persistent crisis starts from event data")
	WorldResolverScript.apply_persistent_crises(crisis_game.countries, crisis_game.world)
	_assert(int(crisis_game.world.tracks.get("international_financial_instability", 0)) == 2, "persistent crisis applies recurring world effects")
	_assert(int(crisis_game.world.active_crises[0].get("turns", 0)) == 1, "persistent crisis tracks remaining turns")
	crisis_game.world.tracks["global_coordination"] = 4
	var clear_log: Array = WorldResolverScript.apply_persistent_crises(crisis_game.countries, crisis_game.world)
	_assert(crisis_game.world.active_crises.is_empty(), "persistent crisis clears when condition is met")
	_assert(_contains(clear_log, "解除条件"), "persistent crisis clear is logged")

	var injection_game = GameStateScript.new()
	injection_game.new_game()
	var reserve_menu_before := _policy_menu_has(injection_game.countries[0], "last_resort_lender")
	injection_game.world.event_deck = [{
		"id": "test_asymmetric_event",
		"display_name": "試験非対称イベント",
		"message": "試験",
		"effects": {
			"world": {"international_financial_instability": 1},
			"tagged_countries": [
				{"tag": "exporter", "effects": {}, "add_state_cards": ["external_demand_dependence"]},
				{"tag": "reserve_currency", "effects": {}, "add_policy_menu": ["last_resort_lender"]}
			]
		}
	}]
	WorldResolverScript.reveal_event(injection_game.world, injection_game.countries, injection_game.rng, injection_game.card_index, injection_game.policy_index)
	_assert(String(injection_game.countries[1].deck[0].get("id", "")) == "external_demand_dependence", "world event stamps exporter history into the state deck")
	_assert(not reserve_menu_before and _policy_menu_has(injection_game.countries[0], "last_resort_lender"), "world event grants reserve-currency crisis policy")
	_assert(_policy_menu_has_source(injection_game.countries[0], "crisis:"), "world event labels crisis-granted policy menu options")
	_assert(_policy_catalog_has(injection_game.countries[0], "last_resort_lender"), "world event adds crisis policy to the policy catalog deck")

	var scores: Array = game.get_scores()
	_assert(scores[0].has("legacy_bonus"), "scores include legacy bonus")
	game.world.tracks["depression"] = 10
	var collapse_scores: Array = game.get_scores()
	_assert(bool(collapse_scores[0].get("global_collapse", false)), "scores mark global collapse at depression 10")
	_assert(int(collapse_scores[0].get("score", -1)) == 0, "global collapse invalidates country scores")
	if had_failure:
		print("Smoke domain rules failed.")
		quit(1)
	else:
		print("Smoke domain rules passed.")
		quit(0)

func _first_policy_index(hand: Array) -> int:
	for i in range(hand.size()):
		if hand[i].get("type", "") == "policy":
			return i
	return -1

func _contains(lines: Array, needle: String) -> bool:
	for line in lines:
		if String(line).contains(needle):
			return true
	return false

func _policy_menu_has(country, policy_id: String) -> bool:
	for policy in country.policy_menu:
		if String(policy.get("id", "")) == policy_id:
			return true
	return false

func _basic_policy_count(cards: Array) -> int:
	var count := 0
	for card in cards:
		var policy_id := String(card.get("id", ""))
		if ["fiscal_stimulus", "austerity", "policy_rate_hike", "rate_cut_and_qe", "social_safety_net"].has(policy_id):
			count += 1
	return count

func _policy_catalog_menu_count(country) -> int:
	var count := 0
	for policy in country.policy_menu:
		var policy_id := String(policy.get("id", ""))
		if not ["fiscal_stimulus", "austerity", "policy_rate_hike", "rate_cut_and_qe", "social_safety_net"].has(policy_id):
			count += 1
	return count

func _policy_catalog_has(country, policy_id: String) -> bool:
	for zone in [country.policy_catalog_deck, country.policy_catalog_discard, country.active_agenda]:
		for policy in zone:
			if String(policy.get("id", "")) == policy_id:
				return true
	return false

func _policy_ids(cards: Array) -> Array:
	var ids := []
	for card in cards:
		ids.append(String(card.get("id", "")))
	return ids

func _all_policy_menu_sources_present(country) -> bool:
	for policy in country.policy_menu:
		if String(policy.get("_menu_source", "")).is_empty():
			return false
	return true

func _policy_menu_has_source(country, source_prefix: String) -> bool:
	for policy in country.policy_menu:
		if String(policy.get("_menu_source", "")).begins_with(source_prefix):
			return true
	return false

func _all_agenda_from_catalog_or_basic(country) -> bool:
	var catalog_ids := []
	for policy in country.policy_menu:
		catalog_ids.append(String(policy.get("id", "")))
	for policy in country.active_agenda:
		var policy_id := String(policy.get("id", ""))
		if not catalog_ids.has(policy_id):
			return false
	return true

func _policy_count(cards: Array) -> int:
	var count := 0
	for card in cards:
		if String(card.get("type", "")) == "policy":
			count += 1
	return count

func _first_basic_policy(cards: Array) -> Dictionary:
	for card in cards:
		var policy_id := String(card.get("id", ""))
		if ["fiscal_stimulus", "austerity", "policy_rate_hike", "rate_cut_and_qe", "social_safety_net"].has(policy_id):
			return card
	return {}

func _seed_test_agenda(country, policies: Array) -> void:
	var agenda := []
	for policy in policies:
		agenda.append(policy)
	var filler_index := 0
	for policy in country.policy_menu:
		if agenda.size() >= 4:
			break
		if _policy_ids(agenda).has(String(policy.get("id", ""))):
			continue
		agenda.append(policy)
	while agenda.size() < 4:
		agenda.append({
			"id": "test_filler_%d" % filler_index,
			"display_name": "試験用政策%d" % filler_index,
			"type": "policy",
			"catalog_type": "basic",
			"source": "basic",
			"tags": [],
			"costs": {},
			"effects": {"country": {}, "world": {}}
		})
		filler_index += 1
	country.policy_menu = agenda.duplicate(true)
	country.active_agenda = agenda.duplicate(true)

func _agenda_has(country, policy_id: String) -> bool:
	for policy in country.active_agenda:
		if String(policy.get("id", "")) == policy_id:
			return true
	return false

func _assert(condition: bool, message: String) -> void:
	if condition:
		return
	had_failure = true
	push_error(message)
