extends SceneTree

const GameStateScript := preload("res://src/core/game_state.gd")
const PolicyRecommenderScript := preload("res://src/app/policy_recommender.gd")

const RUNS := 80
const OUTPUT_PATH := "res://docs/balancing_notes.md"

func _init() -> void:
	var wins := {}
	var collapse_count := 0
	var total_scores := {}
	for run_index in range(RUNS):
		var game = GameStateScript.new()
		game.new_game(20260617 + run_index)
		while not game.is_finished:
			if game.current_phase() == "negotiation":
				_declare_recommended_cooperation(game)
				game.advance_phase()
			elif game.current_phase() == "policy_planning":
				_select_recommended_policies(game)
				game.advance_phase()
			elif game.current_phase() == "worker_assignment":
				_assign_recommended_workers(game)
				game.advance_phase()
			elif game.current_phase() == "simultaneous_reveal":
				game.advance_phase()
			else:
				game.advance_phase()
		var scores: Array = game.get_scores()
		if not scores.is_empty() and bool(scores[0].get("global_collapse", false)):
			collapse_count += 1
		elif not scores.is_empty():
			var winner := String(scores[0].get("country_id", ""))
			wins[winner] = int(wins.get(winner, 0)) + 1
		for score in scores:
			var country_id := String(score.get("country_id", ""))
			total_scores[country_id] = int(total_scores.get(country_id, 0)) + int(score.get("score", 0))
	_write_notes(wins, collapse_count, total_scores)
	print("Monte Carlo balance complete: %d runs" % RUNS)
	quit(0)

func _declare_recommended_cooperation(game) -> void:
	for i in range(game.countries.size()):
		var recommendation := PolicyRecommenderScript.recommend_for_country(game, i)
		if recommendation.is_empty():
			continue
		var options: Array = game.policy_options(i)
		var policy_index := int(recommendation.get("policy_index", -1))
		if policy_index < 0 or policy_index >= options.size():
			continue
		var card: Dictionary = options[policy_index]
		if card.get("tags", []).has("cooperation"):
			game.declare_agenda(i, "cooperation")

func _select_recommended_policies(game) -> void:
	for i in range(game.countries.size()):
		var recommendation := PolicyRecommenderScript.recommend_for_country(game, i)
		if recommendation.is_empty():
			continue
		game.select_policy(i, int(recommendation["policy_index"]))

func _assign_recommended_workers(game) -> void:
	for i in range(game.countries.size()):
		var recommendation := PolicyRecommenderScript.recommend_for_country(game, i)
		if recommendation.is_empty():
			continue
		game.assign_worker(i, String(recommendation["worker"]))

func _write_notes(wins: Dictionary, collapse_count: int, total_scores: Dictionary) -> void:
	var lines := []
	lines.append("# Balancing Notes\n")
	lines.append("Generated by `tools/monte_carlo_balance.gd` using `%d` PolicyRecommender games.\n" % RUNS)
	lines.append("## Results\n")
	lines.append("| Metric | Value |")
	lines.append("|---|---:|")
	lines.append("| Global collapse rate | %.1f%% |" % (float(collapse_count) * 100.0 / float(RUNS)))
	for country_id in total_scores.keys():
		var win_rate := float(wins.get(country_id, 0)) * 100.0 / float(RUNS)
		var average_score := float(total_scores[country_id]) / float(RUNS)
		lines.append("| %s win rate | %.1f%% |" % [country_id, win_rate])
		lines.append("| %s average score | %.1f |" % [country_id, average_score])
	var file := FileAccess.open(OUTPUT_PATH, FileAccess.WRITE)
	if file == null:
		push_error("Cannot write %s" % OUTPUT_PATH)
		quit(1)
		return
	file.store_string("\n".join(lines) + "\n")
